#!/usr/bin/env python3
"""Generate the release capability matrix from explicit implementation and scope records."""
import argparse
import json
from pathlib import Path
import subprocess


STATUSES = {'planned', 'partial', 'implemented', 'accepted'}


def load(root):
    """Load and validate the complete remaining issue inventory.
    Takes the repository root; returns issue, scope, stack and capability records or refuses inconsistent claims.
    """
    read = lambda name: json.loads((root / 'docs/backlog' / name).read_text())
    issues, scope, stack, status = map(read, ('remaining-issues.json', 'release-scope.json', 'previous-stack.json', 'capability-status.json'))
    numbers = [issue['number'] for issue in issues]
    if numbers != list(range(129, 358)) or len(set(numbers)) != len(numbers):
        raise ValueError('Remaining issue inventory must contain each issue #129–#357 exactly once, in order')
    if [row['issue'] for row in stack] != list(range(2, 129)):
        raise ValueError('Previous stack inventory must cover each issue #2–#128')
    excluded = scope['excluded_issues']
    if len(set(excluded)) != len(excluded) or not set(excluded) <= set(numbers):
        raise ValueError('Release exclusions must name unique remaining issues')
    if status['schema'] != 1:
        raise ValueError('Unsupported capability registry schema')
    for key, record in status['issues'].items():
        if str(int(key)) != key or int(key) not in numbers or int(key) in excluded:
            raise ValueError(f'Invalid or excluded capability issue {key}')
        if record['status'] not in STATUSES or record['status'] == 'planned':
            raise ValueError(f'Use the inventory default for planned issue {key}')
        if not record['paths'] or not record['fixtures'] or not record['limits']:
            raise ValueError(f'Issue {key} needs reachable paths, fixtures and explicit validation limits')
        for path in record['paths']:
            source = root / path['file']
            if source.is_symlink() or not source.is_file() or not source.resolve().is_relative_to(root.resolve()):
                raise ValueError(f'Issue {key} names an unavailable source route')
            if not path['kind'] or not path['entry']:
                raise ValueError(f'Issue {key} has an unnamed entry point')
        if record['status'] == 'accepted':
            if not record.get('evidence') or record.get('acceptance') != 'all criteria passed':
                raise ValueError(f'Issue {key} cannot be accepted without explicit complete evidence')
            for name in record['evidence']:
                evidence = root / name
                if evidence.is_symlink() or not evidence.is_file() or not evidence.resolve().is_relative_to(root.resolve()):
                    raise ValueError(f'Issue {key} has unavailable acceptance evidence')
    return issues, scope, stack, status


def render(root):
    """Render only the recorded capability status.
    Takes the validated repository; returns deterministic release documentation without turning exclusions or queued work into completion.
    """
    issues, scope, stack, status = load(root)
    clean = lambda text: text.replace('|', '\\|').replace('\n', ' ')
    lines = ['# Capability and compatibility matrix', '',
             f"Generated by `python3 scripts/capability-matrix.py generate`. Release: {status['release']}. Reviewed: {status['reviewed']}.", '',
             'Planned means no complete implementation is claimed. Partial means some work is present. Implemented still awaits complete acceptance qualification. Accepted requires the recorded acceptance evidence. Excluded means a release decision, not a completed issue. Earlier stacked PRs remain reviewable work and are not requalified by this matrix.', '',
             '## Stable reference review', '']
    for reference in status['references']:
        lines.append(f"- [{reference['name']} {reference['stable']}]({reference['url']}): {reference['scope']}")
    lines += ['', '## Observed compatibility', '', '| Target | Recorded status | Exact versions | Limits |', '| --- | --- | --- | --- |']
    for row in status['compatibility']:
        lines.append('| ' + ' | '.join(clean(row[key]) for key in ('name', 'status', 'versions', 'limits')) + ' |')
    lines += ['', '## Implemented paths and acceptance fixtures', '']
    for key, record in sorted(status['issues'].items(), key=lambda pair: int(pair[0])):
        lines += [f"### Issue #{key}: {record['status']}", '']
        for path in record['paths']:
            lines.append(f"- {path['kind']}: [{path['file']}](../{path['file']}) — {path['entry']}")
        lines += [f"- Acceptance fixtures: {', '.join('`' + fixture + '`' for fixture in record['fixtures'])}."]
        for evidence in record.get('evidence', []):
            lines.append(f'- Evidence: [{evidence}](../{evidence}).')
        lines += ['', record['limits'], '']
    lines += ['## One remaining checklist', '', f"Music source: {scope['music_source']}. {scope['scope_note']}", '', '| Issue | Capability | Status |', '| --- | --- | --- |']
    for issue in issues:
        number = issue['number']
        state = 'excluded from release' if number in scope['excluded_issues'] else status['issues'].get(str(number), {}).get('status', 'planned')
        lines.append(f"| [#{number}]({issue['html_url']}) | {clean(issue['title'].removeprefix('[feat]/ '))} | {state} |")
    lines += ['', '## Earlier stack', '', 'Issues #2–#128 are already represented below the combined PR. These links describe live open-PR inventory taken on 2026-10-03; merge state is not inferred.', '', '| Issue | Capability | Existing PRs |', '| --- | --- | --- |']
    for row in stack:
        links = ', '.join(f"[#{url.rsplit('/', 1)[-1]}]({url})" for url in row['prs']) or 'Additional mapping review required'
        lines.append(f"| #{row['issue']} | {clean(row['title'])} | {links} |")
    return '\n'.join(lines) + '\n'


def verify_fixture_names(status, names):
    """Check that every registered Rust acceptance fixture exists.
    Takes the registry and compiled test names; refuses missing or zero-match selectors without claiming those tests passed.
    """
    for key, record in status['issues'].items():
        for fixture in record['fixtures']:
            if not fixture.startswith('scripts/') and not any(name == fixture or name.startswith(fixture + '::') for name in names):
                raise ValueError(f'Issue {key} fixture has no compiled tests: {fixture}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('action', choices=('generate', 'check'))
    parser.add_argument('--test-binary', type=Path, help='verify Rust selectors against this actual compiled test inventory; does not substitute for running tests')
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    destination = root / 'docs/capability-matrix.md'
    try:
        expected = render(root)
        if args.action == 'generate':
            destination.write_text(expected)
        elif not destination.is_file() or destination.read_text() != expected:
            raise ValueError('Capability matrix is stale; run generate after reviewing the registry')
        if args.test_binary:
            result = subprocess.run([str(args.test_binary.resolve()), '--list'], capture_output=True, text=True, check=True, timeout=15)
            names = [line.removesuffix(': test') for line in result.stdout.splitlines() if line.endswith(': test')]
            if not names or len(names) > 10000:
                raise ValueError('Unavailable or oversized compiled acceptance fixture inventory')
            verify_fixture_names(load(root)[3], names)
    except (ValueError, KeyError, OSError) as error:
        parser.exit(1, f'Capability matrix refused: {error}\n')
    print(f'Capability matrix {args.action}: passed')
