#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const statuses = new Set(['partial', 'implemented', 'accepted']);

/** Load qualified capability records. Takes a repository root; returns validated inventory and refuses missing routes or unsupported acceptance claims. */
export function load(directory = root) {
    const read = name => JSON.parse(fs.readFileSync(path.join(directory, 'docs/backlog', name), 'utf8'));
    const issues = read('remaining-issues.json'), scope = read('release-scope.json'), stack = read('previous-stack.json'), status = read('capability-status.json');
    if (issues.length !== 229 || issues.some((issue, index) => issue.number !== index + 129)) throw new Error('Remaining issue inventory must contain each issue #129–#357 exactly once, in order');
    if (stack.length !== 127 || stack.some((row, index) => row.issue !== index + 2)) throw new Error('Previous stack must contain each issue #2–#128');
    const numbers = new Set(issues.map(issue => issue.number)), excluded = new Set(scope.excluded_issues);
    if (excluded.size !== scope.excluded_issues.length || scope.excluded_issues.some(issue => !numbers.has(issue))) throw new Error('Invalid release exclusions');
    if (status.schema !== 1) throw new Error('Unsupported capability registry schema');
    const available = file => {
        const target = path.resolve(directory, file);
        return target.startsWith(path.resolve(directory) + path.sep) && fs.existsSync(target) && !fs.lstatSync(target).isSymbolicLink() && fs.statSync(target).isFile() && fs.realpathSync(target).startsWith(fs.realpathSync(directory) + path.sep);
    };
    for (const [key, record] of Object.entries(status.issues)) {
        if (String(Number(key)) !== key || !numbers.has(Number(key)) || excluded.has(Number(key))) throw new Error(`Invalid or excluded capability issue ${key}`);
        if (!statuses.has(record.status) || !record.paths?.length || !record.fixtures?.length || !record.limits) throw new Error(`Issue ${key} needs status, source routes, fixtures and limits`);
        for (const route of record.paths) if (!available(route.file) || !route.kind || !route.entry) throw new Error(`Issue ${key} has an unavailable source route`);
        if (record.status === 'accepted') {
            if (!record.evidence?.length || record.acceptance !== 'all criteria passed') throw new Error(`Issue ${key} cannot be accepted without explicit complete evidence`);
            for (const file of record.evidence) if (!available(file)) throw new Error(`Issue ${key} has unavailable acceptance evidence`);
        }
    }
    return { issues, scope, stack, status };
}

/** Render recorded capability state. Takes a repository root; returns deterministic documentation without inferring completion from implementation. */
export function render(directory = root) {
    const { issues, scope, stack, status } = load(directory);
    const clean = text => text.replaceAll('|', '\\|').replaceAll('\n', ' ');
    const lines = ['# Capability and compatibility matrix', '',
        `Generated by \`node scripts/capability-matrix.mjs generate\`. Release: ${status.release}. Reviewed: ${status.reviewed}.`, '',
        'Planned means no complete implementation is claimed. Partial means some work is present. Implemented still awaits complete acceptance qualification. Accepted requires the recorded acceptance evidence. Excluded means a release decision, not a completed issue. Earlier stacked PRs remain reviewable work and are not requalified by this matrix.', '',
        '## Stable reference review', ''];
    for (const reference of status.references) lines.push(`- [${reference.name} ${reference.stable}](${reference.url}): ${reference.scope}`);
    lines.push('', '## Observed compatibility', '', '| Target | Recorded status | Exact versions | Limits |', '| --- | --- | --- | --- |');
    for (const row of status.compatibility) lines.push('| ' + ['name', 'status', 'versions', 'limits'].map(key => clean(row[key])).join(' | ') + ' |');
    lines.push('', '## Implemented paths and acceptance fixtures', '');
    for (const [key, record] of Object.entries(status.issues).sort((a, b) => Number(a[0]) - Number(b[0]))) {
        lines.push(`### Issue #${key}: ${record.status}`, '');
        for (const route of record.paths) lines.push(`- ${route.kind}: [${route.file}](../${route.file}) — ${route.entry}`);
        lines.push(`- Acceptance fixtures: ${record.fixtures.map(fixture => '`' + fixture + '`').join(', ')}.`);
        for (const evidence of record.evidence || []) lines.push(`- Evidence: [${evidence}](../${evidence}).`);
        lines.push('', record.limits, '');
    }
    lines.push('## One remaining checklist', '', `Music source: ${scope.music_source}. ${scope.scope_note}`, '', '| Issue | Capability | Status |', '| --- | --- | --- |');
    for (const issue of issues) {
        const state = scope.excluded_issues.includes(issue.number) ? 'excluded from release' : status.issues[issue.number]?.status || 'planned';
        lines.push(`| [#${issue.number}](${issue.html_url}) | ${clean(issue.title.replace(/^\[feat\]\/ /, ''))} | ${state} |`);
    }
    lines.push('', '## Earlier stack', '', 'Issues #2–#128 are already represented below the combined PR. These links describe live open-PR inventory taken on 2026-10-03; merge state is not inferred.', '', '| Issue | Capability | Existing PRs |', '| --- | --- | --- |');
    for (const row of stack) lines.push(`| #${row.issue} | ${clean(row.title)} | ${row.prs.map(url => `[#${url.split('/').at(-1)}](${url})`).join(', ') || 'Additional mapping review required'} |`);
    return lines.join('\n') + '\n';
}

/** Check compiled acceptance selectors. Takes a capability registry and test names; refuses every selector without a matching actual test. */
export function verifyFixtureNames(status, names) {
    for (const [key, record] of Object.entries(status.issues)) for (const fixture of record.fixtures) {
        if (!fixture.startsWith('scripts/') && !names.some(name => name === fixture || name.startsWith(fixture + '::'))) throw new Error(`Issue ${key} fixture has no compiled tests: ${fixture}`);
    }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    const [action, flag, binary] = process.argv.slice(2), result = render(), destination = path.join(root, 'docs/capability-matrix.md');
    if (action === 'generate') fs.writeFileSync(destination, result);
    else if (action !== 'check' || fs.readFileSync(destination, 'utf8') !== result) throw new Error('Capability matrix is stale; run generate after reviewing the registry');
    if (flag) {
        if (flag !== '--test-binary' || !binary) throw new Error('Expected --test-binary PATH');
        const names = execFileSync(path.resolve(binary), ['--list'], { encoding: 'utf8', timeout: 15000 }).split('\n').filter(line => line.endsWith(': test')).map(line => line.slice(0, -6));
        if (!names.length || names.length > 10000) throw new Error('Unavailable or oversized compiled fixture inventory');
        verifyFixtureNames(load().status, names);
    }
    console.log(`Capability matrix ${action}: passed`);
}
